# Generated by Django 5.2.17 on 2026-09-15 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(help_text='Used in the web address.', max_length=80, unique=True)),
                ('description', models.TextField(blank=True, help_text='One or two sentences shown at the top of the category page.')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower numbers appear first. Use 10, 20, 30 so you can insert between later.')),
                ('icon', models.CharField(blank=True, help_text="Optional Material Symbols icon name, e.g. 'groups' or 'sports_soccer'.", max_length=40)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(help_text='Used in the web address.', max_length=160, unique=True)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('show_in_nav', models.BooleanField(default=False, help_text='Tick to add a link to this page in the site header.', verbose_name='show in navigation')),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(help_text='Used in the web address. Leave blank and it will be filled in from the name.', max_length=160, unique=True)),
                ('short_description', models.CharField(help_text='One sentence, plain text. This is what shows in listings and search results.', max_length=240)),
                ('description', models.TextField(blank=True, help_text="The full description shown on the program's own page.")),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, help_text="The program's general contact address.", max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('street', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='ZIP code')),
                ('serves_grades', models.CharField(blank=True, help_text="Free text, e.g. 'K–8' or 'high school only'. Leave blank if it varies.", max_length=80)),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cost_notes', models.TextField(blank=True, help_text="Free text — fee structures never fit a single number. e.g. '$45/semester per family, plus a $20 materials fee'.")),
                ('meeting_schedule', models.TextField(blank=True, help_text="Free text, e.g. 'Tuesdays 9–noon, September through May'.")),
                ('status', models.CharField(choices=[('draft', 'Draft — not visible on the site'), ('published', 'Published — visible to everyone'), ('archived', 'Archived — no longer operating')], db_index=True, default='draft', max_length=16)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured programs appear at the top of the home page.')),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_on', models.DateField(blank=True, help_text='The last date someone confirmed this information is still correct. A directory dies of staleness, not of missing features.', null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='programs', to='directory.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, help_text="e.g. 'Coordinator', 'Registration'.", max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_public', models.BooleanField(default=False, help_text="Untick to keep this person's details for our records only. Only ticked contacts appear on the public site.")),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='directory.program')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=160)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True, help_text='What the submitter told us about the program.')),
                ('submitter_name', models.CharField(blank=True, max_length=120)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('new', 'New — needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=16)),
                ('review_notes', models.TextField(blank=True, help_text='For our records. Never shown publicly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='directory.category')),
                ('created_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_submissions', to='directory.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
