# Generated by Django 5.2.17 on 2026-09-15 01:00

import directory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='age_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='age_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='submission',
            name='contact_is_public',
            field=models.BooleanField(default=True, help_text="Whether this contact's details may appear on the public page."),
        ),
        migrations.AddField(
            model_name='submission',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='submission',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='submission',
            name='contact_role',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='submission',
            name='cost_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='The registrant confirmed they are authorized to list this program.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='kind',
            field=models.CharField(choices=[('registration', "Registration — the provider's own program"), ('referral', 'Referral — someone else suggested it')], db_index=True, default='registration', max_length=16),
        ),
        migrations.AddField(
            model_name='submission',
            name='logo',
            field=models.ImageField(blank=True, upload_to='submissions/logos/', validators=[directory.models.validate_logo_size]),
        ),
        migrations.AddField(
            model_name='submission',
            name='meeting_schedule',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='serves_grades',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='submission',
            name='short_description',
            field=models.CharField(blank=True, help_text='One sentence, plain text. Shown in listings and search results.', max_length=240),
        ),
        migrations.AddField(
            model_name='submission',
            name='street',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitter_role',
            field=models.CharField(blank=True, help_text='Their role at the program, for registrations.', max_length=80),
        ),
        migrations.AddField(
            model_name='submission',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='ZIP code'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True, help_text='The full description, as plain text. Blank lines start new paragraphs.'),
        ),
    ]
