# Generated by Django 5.2.17 on 2026-09-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0003_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="facebook",
            field=models.URLField(
                blank=True,
                help_text="The full address of their Facebook page or group, e.g. 'https://facebook.com/groups/example'.",
                verbose_name="Facebook page",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="facebook",
            field=models.URLField(blank=True, verbose_name="Facebook page"),
        ),
    ]
