# Generated by Django 5.2.17 on 2026-09-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0006_drop_contact_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="step_up_direct_pay",
            field=models.BooleanField(
                default=False,
                help_text="Tick if families can pay this program directly through Step Up For Students' EMA marketplace.",
                verbose_name="Step Up direct pay provider",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="step_up_fes_ua",
            field=models.BooleanField(
                default=False,
                help_text="Family Empowerment Scholarship for Students with Unique Abilities.",
                verbose_name="direct pay for FES-UA",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="step_up_pep",
            field=models.BooleanField(
                default=False,
                help_text="Personalized Education Program.",
                verbose_name="direct pay for PEP",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="step_up_direct_pay",
            field=models.BooleanField(default=False, verbose_name="Step Up direct pay provider"),
        ),
        migrations.AddField(
            model_name="submission",
            name="step_up_fes_ua",
            field=models.BooleanField(default=False, verbose_name="direct pay for FES-UA"),
        ),
        migrations.AddField(
            model_name="submission",
            name="step_up_pep",
            field=models.BooleanField(default=False, verbose_name="direct pay for PEP"),
        ),
    ]
