# Generated by Django 5.2.17 on 2026-09-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0007_step_up"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in the web address. Leave blank and it will be filled in from the name.",
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional. One or two sentences shown at the top of the tag's page.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="program",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="The finer taxonomy. Add as many as genuinely apply — tags are how someone finds a program they could not have guessed the category of.",
                related_name="programs",
                to="directory.tag",
            ),
        ),
    ]
