# Generated by Django 5.2.17 on 2026-09-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0008_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="tags",
            field=models.ManyToManyField(blank=True, to="directory.tag"),
        ),
    ]
