# Generated by Django 5.2.17 on 2026-09-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_single_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags a registrant may choose after picking this heading. A tag can appear under more than one heading. A tag under no heading is ours to apply here in the admin and is never offered on the public form.', related_name='categories', to='directory.tag'),
        ),
    ]
