"""The thirteen kinds of program, as columns.

Nothing here is destructive and nothing needs a data step. The additions are all
optional, and the `AlterField` operations are help text and labels catching up
with the fact that `Program` and `Submission` now declare their shared fields in
one place instead of two — the columns themselves are unchanged.

`TagGroup` arrives with no rows. `manage.py seed_taxonomy` fills it, along with
the thirteen headings the field map in `questions.py` expects to find.
"""

# Generated by Django 5.2.17 on 2026-09-29 00:45

import directory.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_submitted_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The question, worded as a label: "Ability level", "Parent involvement".', max_length=60, unique=True)),
                ('slug', models.SlugField(help_text='Used in the web address when someone filters by this. Leave blank and it will be filled in from the name.', max_length=60, unique=True)),
                ('prompt', models.CharField(blank=True, help_text='Optional. A sentence under the question on the registration form.', max_length=200)),
                ('allows_several', models.BooleanField(default=True, help_text='Tick when a program can honestly pick several — a class may suit beginners and intermediates both. Untick when the answers are alternatives.', verbose_name='more than one answer')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='Lower numbers appear first on the form.')),
            ],
            options={
                'verbose_name': 'tag question',
                'verbose_name_plural': 'tag questions',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='class_names',
            field=models.CharField(blank=True, help_text="The individual classes, separated by commas — e.g. 'Algebra I, Geometry, Chemistry'.", max_length=240, verbose_name='classes offered'),
        ),
        migrations.AddField(
            model_name='program',
            name='cost_basis',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('paid', 'There is a cost'), ('varies', 'Varies')], help_text='The headline answer. The detail goes in the box below.', max_length=8, verbose_name='cost'),
        ),
        migrations.AddField(
            model_name='program',
            name='delivery',
            field=models.CharField(blank=True, choices=[('in_person', 'In person'), ('online', 'Online'), ('hybrid', 'In person or online')], help_text='Leave blank if they have not told us.', max_length=10, verbose_name='in person or online'),
        ),
        migrations.AddField(
            model_name='program',
            name='enrollment_closes',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='enrollment_notes',
            field=models.CharField(blank=True, help_text="e.g. 'rolling admission' or 'waiting list only'.", max_length=160, verbose_name='enrollment, in words'),
        ),
        migrations.AddField(
            model_name='program',
            name='enrollment_opens',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='faith_basis',
            field=models.CharField(blank=True, choices=[('faith', 'Faith-based'), ('secular', 'Not faith-based')], help_text="Leave blank if they have not told us. 'Not faith-based' is a different answer from no answer, and both are fine to publish.", max_length=8, verbose_name='faith affiliation'),
        ),
        migrations.AddField(
            model_name='program',
            name='highlights',
            field=models.TextField(blank=True, help_text='Plain text. What a family gets here that they would not get elsewhere. Blank lines start new paragraphs.', verbose_name='what makes it special'),
        ),
        migrations.AddField(
            model_name='program',
            name='host_name',
            field=models.CharField(blank=True, help_text='The larger group this runs under, when the listing is a class or a team rather than the group itself. Leave blank when they are the same thing.', max_length=120, verbose_name='host or group name'),
        ),
        migrations.AddField(
            model_name='program',
            name='instructor_info',
            field=models.TextField(blank=True, help_text='Who teaches, and what qualifies them. Families ask this before they ask almost anything else.', verbose_name='teachers and qualifications'),
        ),
        migrations.AddField(
            model_name='program',
            name='meeting_days',
            field=directory.models.WeekdaysField(blank=True, help_text='Tick every day they normally meet.', validators=[directory.models.validate_weekdays], verbose_name='days they meet'),
        ),
        migrations.AddField(
            model_name='program',
            name='meeting_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='ends at'),
        ),
        migrations.AddField(
            model_name='program',
            name='meeting_time_start',
            field=models.TimeField(blank=True, help_text='Leave blank if it varies.', null=True, verbose_name='starts at'),
        ),
        migrations.AddField(
            model_name='program',
            name='season_end',
            field=models.DateField(blank=True, null=True, verbose_name='last meeting'),
        ),
        migrations.AddField(
            model_name='program',
            name='season_start',
            field=models.DateField(blank=True, help_text='The date this season or term starts. Leave blank if they run year round or have not set one.', null=True, verbose_name='first meeting'),
        ),
        migrations.AddField(
            model_name='program',
            name='service_area',
            field=models.CharField(blank=True, help_text="e.g. 'west Volusia only' or 'up to 30 miles'. For programs with no one fixed address.", max_length=160, verbose_name='how far they travel'),
        ),
        migrations.AddField(
            model_name='program',
            name='travels_to_student_home',
            field=models.BooleanField(default=False, help_text='Tick if they come to the family rather than the other way round.', verbose_name='will travel to the student'),
        ),
        migrations.AddField(
            model_name='submission',
            name='class_names',
            field=models.CharField(blank=True, help_text="The individual classes, separated by commas — e.g. 'Algebra I, Geometry, Chemistry'.", max_length=240, verbose_name='classes offered'),
        ),
        migrations.AddField(
            model_name='submission',
            name='cost_basis',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('paid', 'There is a cost'), ('varies', 'Varies')], help_text='The headline answer. The detail goes in the box below.', max_length=8, verbose_name='cost'),
        ),
        migrations.AddField(
            model_name='submission',
            name='delivery',
            field=models.CharField(blank=True, choices=[('in_person', 'In person'), ('online', 'Online'), ('hybrid', 'In person or online')], help_text='Leave blank if they have not told us.', max_length=10, verbose_name='in person or online'),
        ),
        migrations.AddField(
            model_name='submission',
            name='enrollment_closes',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='enrollment_notes',
            field=models.CharField(blank=True, help_text="e.g. 'rolling admission' or 'waiting list only'.", max_length=160, verbose_name='enrollment, in words'),
        ),
        migrations.AddField(
            model_name='submission',
            name='enrollment_opens',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='faith_basis',
            field=models.CharField(blank=True, choices=[('faith', 'Faith-based'), ('secular', 'Not faith-based')], help_text="Leave blank if they have not told us. 'Not faith-based' is a different answer from no answer, and both are fine to publish.", max_length=8, verbose_name='faith affiliation'),
        ),
        migrations.AddField(
            model_name='submission',
            name='highlights',
            field=models.TextField(blank=True, help_text='Plain text. What a family gets here that they would not get elsewhere. Blank lines start new paragraphs.', verbose_name='what makes it special'),
        ),
        migrations.AddField(
            model_name='submission',
            name='host_name',
            field=models.CharField(blank=True, help_text='The larger group this runs under, when the listing is a class or a team rather than the group itself. Leave blank when they are the same thing.', max_length=120, verbose_name='host or group name'),
        ),
        migrations.AddField(
            model_name='submission',
            name='instructor_info',
            field=models.TextField(blank=True, help_text='Who teaches, and what qualifies them. Families ask this before they ask almost anything else.', verbose_name='teachers and qualifications'),
        ),
        migrations.AddField(
            model_name='submission',
            name='meeting_days',
            field=directory.models.WeekdaysField(blank=True, help_text='Tick every day they normally meet.', validators=[directory.models.validate_weekdays], verbose_name='days they meet'),
        ),
        migrations.AddField(
            model_name='submission',
            name='meeting_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='ends at'),
        ),
        migrations.AddField(
            model_name='submission',
            name='meeting_time_start',
            field=models.TimeField(blank=True, help_text='Leave blank if it varies.', null=True, verbose_name='starts at'),
        ),
        migrations.AddField(
            model_name='submission',
            name='season_end',
            field=models.DateField(blank=True, null=True, verbose_name='last meeting'),
        ),
        migrations.AddField(
            model_name='submission',
            name='season_start',
            field=models.DateField(blank=True, help_text='The date this season or term starts. Leave blank if they run year round or have not set one.', null=True, verbose_name='first meeting'),
        ),
        migrations.AddField(
            model_name='submission',
            name='service_area',
            field=models.CharField(blank=True, help_text="e.g. 'west Volusia only' or 'up to 30 miles'. For programs with no one fixed address.", max_length=160, verbose_name='how far they travel'),
        ),
        migrations.AddField(
            model_name='submission',
            name='travels_to_student_home',
            field=models.BooleanField(default=False, help_text='Tick if they come to the family rather than the other way round.', verbose_name='will travel to the student'),
        ),
        migrations.AlterField(
            model_name='program',
            name='cost_notes',
            field=models.TextField(blank=True, help_text="Free text — fee structures never fit a single number. e.g. '$45/semester per family, plus a $20 materials fee'.", verbose_name='cost, in detail'),
        ),
        migrations.AlterField(
            model_name='program',
            name='meeting_schedule',
            field=models.TextField(blank=True, help_text="Free text, for what the boxes above cannot say — e.g. 'alternate Tuesdays' or 'times vary by class'.", verbose_name='anything else about when'),
        ),
        migrations.AlterField(
            model_name='program',
            name='serves_grades',
            field=models.CharField(blank=True, help_text="Free text, e.g. 'K-8' or 'high school only'. Leave blank if it varies.", max_length=80),
        ),
        migrations.AlterField(
            model_name='submission',
            name='cost_notes',
            field=models.TextField(blank=True, help_text="Free text — fee structures never fit a single number. e.g. '$45/semester per family, plus a $20 materials fee'.", verbose_name='cost, in detail'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.EmailField(blank=True, help_text="The program's general contact address.", max_length=254),
        ),
        migrations.AlterField(
            model_name='submission',
            name='facebook',
            field=models.URLField(blank=True, help_text="The full address of their Facebook page or group, e.g. 'https://facebook.com/groups/example'.", verbose_name='Facebook page'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='meeting_schedule',
            field=models.TextField(blank=True, help_text="Free text, for what the boxes above cannot say — e.g. 'alternate Tuesdays' or 'times vary by class'.", verbose_name='anything else about when'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='serves_grades',
            field=models.CharField(blank=True, help_text="Free text, e.g. 'K-8' or 'high school only'. Leave blank if it varies.", max_length=80),
        ),
        migrations.AlterField(
            model_name='submission',
            name='step_up_direct_pay',
            field=models.BooleanField(default=False, help_text="Tick if families can pay this program directly through Step Up For Students' EMA marketplace.", verbose_name='Step Up direct pay provider'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='step_up_fes_ua',
            field=models.BooleanField(default=False, help_text='Family Empowerment Scholarship for Students with Unique Abilities.', verbose_name='direct pay for FES-UA'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='step_up_pep',
            field=models.BooleanField(default=False, help_text='Personalized Education Program.', verbose_name='direct pay for PEP'),
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Leave blank for an ordinary subject tag. Set it and this tag becomes one of the answers to that question, asked of any heading that offers it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='directory.taggroup'),
        ),
    ]
