# Generated by Django 5.2.17 on 2026-09-22 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(editable=False, help_text="Google's permanent identifier for this person. Never reused.", max_length=255, unique=True, verbose_name='Google subject ID')),
                ('email', models.EmailField(editable=False, help_text='The address Google reported at the last sign-in.', max_length=254, verbose_name='Google email address')),
                ('linked_on', models.DateTimeField(auto_now_add=True)),
                ('last_used_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_link', to=settings.AUTH_USER_MODEL, verbose_name='account')),
            ],
            options={
                'verbose_name': 'linked Google account',
                'verbose_name_plural': 'linked Google accounts',
            },
        ),
    ]
